feat: add Inventory
candid-monster/client-team pull request #13
Opened 2023-09-05 04:42 UTC by 20192094

+인벤토리 드래그
+인벤토리 내 아이템 드래그 앤 드랍
+인벤토리 내 아이템 버리기
+인벤토리 아이템 설명창 나타내기
+인벤토리 내 아이템 장착 및 소모

소모품은 갯수 누적/장비템은 한칸에 한개씩

2023-09-05 04:45 UTC, Lapis0875 commented on Assets/Scripts/Inventory/Consumable.cs
> +    public Item.Item item;
```cs
using Item;
```
Item namespace 미리 사용해주시면 바로 `Item` 이름 그대로 클래스 사용할 수 있어요~

2023-09-05 09:55 UTC, leejung7308 approved these changes
좋슴다

2023-09-05 11:18 UTC, 20192094 commented on Assets/Scripts/Inventory/Consumable.cs
> +    public Item.Item item;
using Item; 을 선언하면 Assets\Scripts\Inventory\Consumable.cs(8,12): error CS0118: 'Item' is a namespace but is used like a type 에러가 발생하는데 이유를 잘 모르겠어서 일단은 직접 접근했습니다!

2023-09-06 06:48 UTC, Lapis0875 requested changes
웬만하면 `Item.Item`으로 쓰는것 보단, 어짜피 Item namespace에 있는 코드들 다 필요하니까
```cs
using namespace Item;
```
이거 걸고 바로 쓰는게 나을 것 같아요.

2023-09-06 06:52 UTC, Lapis0875 requested changes

2023-09-06 06:52 UTC, Lapis0875 commented on Assets/Scripts/Inventory/Consumable.cs
> +    public Item.Item item;
> using Item; 을 선언하면 Assets\Scripts\Inventory\Consumable.cs(8,12): error CS0118: 'Item' is a namespace but is used like a type 에러가 발생하는데 이유를 잘 모르겠어서 일단은 직접 접근했습니다!

앗 죄송해요
```cs
using namespace Item;
```
namespace 사용하는 구문으로 사용해야 해요!

2023-09-06 06:52 UTC, Lapis0875 commented on Assets/Scripts/Inventory/ItemInfo.cs
> +    public void ShowToolTip(Item.Item _item, Vector3 _pos)
여기도 Item namespace 사용하게끔 고쳐주세요~

2023-09-06 06:52 UTC, Lapis0875 commented on Assets/Scripts/Inventory/Inventory.cs
> +    public void AcquireItem(Item.Item _item, int _count = 1)
여기도 Item namespace 사용하게끔 고쳐주세요~

2023-09-06 06:52 UTC, Lapis0875 commented on Assets/Scripts/Inventory/Slot.cs
> +    public Item.Item item; // ȹ���� ������
여기도 Item namespace 사용하게끔 고쳐주세요~

2023-09-06 06:52 UTC, Lapis0875 commented on Assets/Scripts/Player.cs
> +            Item.Item hitObject = collision.gameObject.GetComponent<Consumable>().item;
여기도 Item namespace 사용하게끔 고쳐주세요~

2023-09-08 01:11 UTC, Lapis0875 commented on Assets/Scripts/Inventory/Consumable.cs
> +    public Item.Item item;
> > using Item; 을 선언하면 Assets\Scripts\Inventory\Consumable.cs(8,12): error CS0118: 'Item' is a namespace but is used like a type 에러가 발생하는데 이유를 잘 모르겠어서 일단은 직접 접근했습니다!
> 
> 앗 죄송해요
> 
> ```cs
> using namespace Item;
> ```
> 
> namespace 사용하는 구문으로 사용해야 해요!

오늘의 교훈 : C#공부를 더 하자

```cs
using Item.Item;
using Item.ItemType;
using Item.Weapon;
```
이처럼 사용할 클래스를 각각 명시해서 using 구문 써줘야 하네요. *로 전체 불러오는 기능은 C#에 없는거같아요~

2023-09-09 11:41 UTC, Lapis0875 approved these changes

2023-09-09 11:42 UTC, merged