feat: Monster hit
candid-monster/client-team pull request #14
Opened 2023-09-07 13:46 UTC by leejung7308

몬스터 피격:
- 원거리: 충돌 오브젝트 삭제 후 피격 로그 출력
- 근거리: 피격 로그 출력

버그 수정:
원거리 무기가 상대 오브젝트와 충돌 시 삭제 되도록 설계해서 두 오브젝트가 가까이 붙었을 때 손에 들고 있는 오브젝트까지 삭제시키는 버그가 발생
- 손에 들고 있는 무기의 콜라이더를 비활성화 시키고 발사되는 투사체 오브젝트만 콜라이더를 활성화하는 방법으로 해결

2023-09-08 00:37 UTC, Lapis0875 requested changes
수고했어! 몇가지 중복해서 쓰이는 코드들만 모듈화 하면 더 깔끔해질 것 같아.

2023-09-08 00:37 UTC, Lapis0875 commented on Assets/Scripts/Player.cs
> +            weapon.GetComponent<Collider2D>().enabled = false;
무기 스왑하는 부분들 겹치는 코드가 꽤 많은데, 이거 별도 메소드로 분리해서 코드 재사용성 높이면 어떨까?

2023-09-09 11:34 UTC, 20192094 approved these changes
ㅇㅋㅇㅋ

2023-09-09 11:34 UTC, leejung7308 commented on Assets/Scripts/Player.cs
> +            weapon.GetComponent<Collider2D>().enabled = false;
고쳤습니다

2023-09-09 11:37 UTC, Lapis0875 approved these changes
수고했어~

2023-09-09 11:38 UTC, merged